In [1]:
import pandas as pd
import numpy as np
np.random.seed(100)

In [2]:
#series: é formatado em coluna, diferentemente dos arrays
s = pd.Series([1,2,3, 'ola',6,8])
s

0      1
1      2
2      3
3    ola
4      6
5      8
dtype: object

In [3]:
#series apartir de uma lista
lista = [10,20,30,40,50]

In [4]:
series1 = pd.Series(lista)

In [5]:
#series apartir de um dict
dicionario = {'telefone': 123, 'telefone2': 456, 'telefone3': 789}
series2 = pd.Series(dicionario)

In [6]:
series1[1]

np.int64(20)

In [7]:
series2['telefone3']

np.int64(789)

In [8]:
#series a partir de um array 
arr = np.array([10,20,30,40])
series3 = pd.Series(arr)
series3

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
series4 = pd.Series([1,2,3,4], index = ['br', 'arg', 'usa', 'chi'])

In [10]:
series4

br     1
arg    2
usa    3
chi    4
dtype: int64

In [11]:
series5 = pd.Series([7,8,9,10], index = ['br', 'arg', 'usa', 'uru'])

In [12]:
series4 + series5
#chi e uru nao tem valores nos dois series

arg    10.0
br      8.0
chi     NaN
uru     NaN
usa    12.0
dtype: float64

In [13]:
 #DATAFRAMES
# dataframes a partir de um array
arr = np.random.randint(10,55, size = (4,4))
arr

array([[18, 34, 13, 49],
       [33, 25, 20, 40],
       [44, 12, 44, 24],
       [44, 34, 25, 46]])

In [14]:
df1 = pd.DataFrame(data=arr, index=['a','b','c','d'], columns = ['x','y','z','w'])
df1

    x   y   z   w
a  18  34  13  49
b  33  25  20  40
c  44  12  44  24
d  44  34  25  46

In [15]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
df2 = pd.DataFrame(data=matriz, index=['a','b','c'], columns = ['d','e','f'])
df2

   d  e  f
a  1  2  3
b  4  5  6
c  7  8  9

In [16]:
#atraves de um dict
dados = {'Produtos': ['VideoGame', 'PC', 'Teclado', 'Mouse'], 'Preço': [5000.00, 4000.00, 150.00, 75.00]}
df3 = pd.DataFrame(data = dados)
df3

    Produtos   Preço
0  VideoGame  5000.0
1         PC  4000.0
2    Teclado   150.0
3      Mouse    75.0

In [17]:
df3['Custo'] = [3500.00, 2750.00, 45.00, 25.00]
df3['Lucro'] = df3['Preço'] - df3['Custo']
df3

    Produtos   Preço   Custo   Lucro
0  VideoGame  5000.0  3500.0  1500.0
1         PC  4000.0  2750.0  1250.0
2    Teclado   150.0    45.0   105.0
3      Mouse    75.0    25.0    50.0

In [18]:
indices = ['Janeiro', 'Março', 'Maio', 'Julho', 'Agosto', 'Outubro' ,'Dezembro']
colunas = np.arange(1,32)
dados = np.random.randint(492, 2050, size=(7,31))

In [19]:
df = pd.DataFrame(data=dados, index=indices, columns=colunas)
df

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Janeiro,1832,1404,2023,1609,578,878,907,1389,1657,1249,...,1852,494,1381,1109,970,1919,555,1697,775,1754
Março,1885,1436,1819,1298,664,766,684,1444,1422,929,...,1338,1516,505,1701,1976,854,623,1074,1728,886
Maio,1731,2018,987,1135,1365,1692,1696,528,1331,530,...,1772,1254,718,1407,688,938,1310,1968,911,899
Julho,1257,2037,1436,2012,901,1954,754,1638,1702,1811,...,1295,1532,2040,1982,1113,1583,712,1739,1280,630
Agosto,1268,965,1204,1930,1505,1865,1379,1048,1761,1573,...,1593,704,877,1530,1805,640,660,1993,934,1288
Outubro,1214,1994,1006,1067,1373,1646,1731,637,1753,1766,...,1377,1285,1710,1147,856,614,503,1105,1496,530
Dezembro,1315,805,579,1183,1246,998,1185,1197,1814,664,...,1834,957,1020,1586,1825,1486,1436,1397,1371,1166

In [20]:
#quanto vendeu no dia 10 dos meses
df[10]

Janeiro     1249
Março        929
Maio         530
Julho       1811
Agosto      1573
Outubro     1766
Dezembro     664
Name: 10, dtype: int64

tipos 

df[] muda de comportamento, pode procurar linhas ou colunas-> 
df.loc[] é consistente no padrão df.loc[linha,coluna]

df[coluna]
df[[coluna1, coluna2, coluna3]]
df[coluna][linha]
df[linha1: linha2]
df.loc[ind linha, indice coluna] -> df.loc['Julho', 30]
df.iloc[ind num linha, indice coluna]-> df.iloc[3, 30]
df.loc[[indlinha1, indlinha2, indlinha3], [col1, col2, col3]]

In [21]:
#quanto vendeu no dia 10,20 e 30 dos meses
df[10]

Janeiro     1249
Março        929
Maio         530
Julho       1811
Agosto      1573
Outubro     1766
Dezembro     664
Name: 10, dtype: int64

In [22]:
df[[10,20,30]]

            10    20    30
Janeiro   1249  1459   775
Março      929   967  1728
Maio       530  1430   911
Julho     1811   581  1280
Agosto    1573  1354   934
Outubro   1766  1145  1496
Dezembro   664   605  1371

In [23]:
df[15]['Março']

np.int64(509)

In [24]:
#quanto vendeu em Janeiro, Agosto e Outubro de 25 a 31 
df.loc[['Julho', 'Agosto', 'Outubro'], [25, 26,27,28,29,30,31]]
df.iloc[[3,4,5], [24,25,26,27,28,29,30]]

           25    26    27   28    29    30    31
Julho    1982  1113  1583  712  1739  1280   630
Agosto   1530  1805   640  660  1993   934  1288
Outubro  1147   856   614  503  1105  1496   530

In [25]:
#selecoes condicionais
df.rename({'Janeiro':'Porta'}, inplace = True)

In [26]:
df

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Porta,1832,1404,2023,1609,578,878,907,1389,1657,1249,...,1852,494,1381,1109,970,1919,555,1697,775,1754
Março,1885,1436,1819,1298,664,766,684,1444,1422,929,...,1338,1516,505,1701,1976,854,623,1074,1728,886
Maio,1731,2018,987,1135,1365,1692,1696,528,1331,530,...,1772,1254,718,1407,688,938,1310,1968,911,899
Julho,1257,2037,1436,2012,901,1954,754,1638,1702,1811,...,1295,1532,2040,1982,1113,1583,712,1739,1280,630
Agosto,1268,965,1204,1930,1505,1865,1379,1048,1761,1573,...,1593,704,877,1530,1805,640,660,1993,934,1288
Outubro,1214,1994,1006,1067,1373,1646,1731,637,1753,1766,...,1377,1285,1710,1147,856,614,503,1105,1496,530
Dezembro,1315,805,579,1183,1246,998,1185,1197,1814,664,...,1834,957,1020,1586,1825,1486,1436,1397,1371,1166

In [27]:
df[df > 1000].fillna('-')

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Porta,1832,1404.0,2023.0,1609,-,-,-,1389.0,1657,1249.0,...,1852,-,1381.0,1109,-,1919.0,-,1697,-,1754.0
Março,1885,1436.0,1819.0,1298,-,-,-,1444.0,1422,-,...,1338,1516.0,-,1701,1976.0,-,-,1074,1728.0,-
Maio,1731,2018.0,-,1135,1365.0,1692.0,1696.0,-,1331,-,...,1772,1254.0,-,1407,-,-,1310.0,1968,-,-
Julho,1257,2037.0,1436.0,2012,-,1954.0,-,1638.0,1702,1811.0,...,1295,1532.0,2040.0,1982,1113.0,1583.0,-,1739,1280.0,-
Agosto,1268,-,1204.0,1930,1505.0,1865.0,1379.0,1048.0,1761,1573.0,...,1593,-,-,1530,1805.0,-,-,1993,-,1288.0
Outubro,1214,1994.0,1006.0,1067,1373.0,1646.0,1731.0,-,1753,1766.0,...,1377,1285.0,1710.0,1147,-,-,-,1105,1496.0,-
Dezembro,1315,-,-,1183,1246.0,-,1185.0,1197.0,1814,-,...,1834,-,1020.0,1586,1825.0,1486.0,1436.0,1397,1371.0,1166.0

In [28]:
df[df>1000][:][[1,2,3,4,5]].fillna('')

             1       2       3     4       5
Porta     1832  1404.0  2023.0  1609
Março     1885  1436.0  1819.0  1298
Maio      1731  2018.0          1135  1365.0
Julho     1257  2037.0  1436.0  2012
Agosto    1268          1204.0  1930  1505.0
Outubro   1214  1994.0  1006.0  1067  1373.0
Dezembro  1315                  1183  1246.0

In [29]:
df[(df[10] > 1000) & (df[15]>1500)].fillna('')

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Agosto,1268,965,1204,1930,1505,1865,1379,1048,1761,1573,...,1593,704,877,1530,1805,640,660,1993,934,1288
Outubro,1214,1994,1006,1067,1373,1646,1731,637,1753,1766,...,1377,1285,1710,1147,856,614,503,1105,1496,530

In [30]:
df[(df[10] > 1000) | (df[15]>1500)].fillna('')

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Porta,1832,1404,2023,1609,578,878,907,1389,1657,1249,...,1852,494,1381,1109,970,1919,555,1697,775,1754
Julho,1257,2037,1436,2012,901,1954,754,1638,1702,1811,...,1295,1532,2040,1982,1113,1583,712,1739,1280,630
Agosto,1268,965,1204,1930,1505,1865,1379,1048,1761,1573,...,1593,704,877,1530,1805,640,660,1993,934,1288
Outubro,1214,1994,1006,1067,1373,1646,1731,637,1753,1766,...,1377,1285,1710,1147,856,614,503,1105,1496,530

In [31]:
#aula 17
#Dataframes multiindex
#antes 1 indice pra coluna e outro pra linha. Agora teremos mais que isso, duas 'linhas' por exemplos, dividifos em levels
lista = [['brasil','brasil', 'brasil', 'argentina', 'argentina', 'argentina'], [2017,2018,2019,2017,2018,2019]]
tuplas = zip(*lista)
tuplas

In [32]:
tuplas = list(tuplas)

In [33]:
multi = pd.MultiIndex.from_tuples(tuplas)
multi

MultiIndex([(   'brasil', 2017),
            (   'brasil', 2018),
            (   'brasil', 2019),
            ('argentina', 2017),
            ('argentina', 2018),
            ('argentina', 2019)],
           )

In [34]:
df0 = pd.DataFrame(data = np.random.randn(6,2), index = multi, columns = ['trigo', 'arroz'])
df0.index.names = ['país', 'ano']
df0

                   trigo     arroz
país      ano
brasil    2017  0.665667  0.463564
          2018 -0.914075  0.891978
          2019 -0.245720  1.337134
argentina 2017 -1.021854 -2.131597
          2018  0.089173 -0.070407
          2019 -1.475935 -0.132252

In [35]:
#encontrando valores em multiindex
df0['arroz']

país       ano
brasil     2017    0.463564
           2018    0.891978
           2019    1.337134
argentina  2017   -2.131597
           2018   -0.070407
           2019   -0.132252
Name: arroz, dtype: float64

In [36]:
df0.loc['brasil']

         trigo     arroz
ano
2017  0.665667  0.463564
2018 -0.914075  0.891978
2019 -0.245720  1.337134

In [37]:
df0.xs(2017,level=1)

              trigo     arroz
país
brasil     0.665667  0.463564
argentina -1.021854 -2.131597

In [38]:
df0.unstack()

              trigo                         arroz
ano            2017      2018      2019      2017      2018      2019
país
argentina -1.021854  0.089173 -1.475935 -2.131597 -0.070407 -0.132252
brasil     0.665667 -0.914075 -0.245720  0.463564  0.891978  1.337134

In [39]:
#aula 18 - joins, similar ao SQL
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                   'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                       'B': ['B4', 'B5', 'B6', 'B7'],
                       'C': ['C4', 'C5', 'C6', 'C7'],
                       'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])
   
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                     'C': ['C8', 'C9', 'C10', 'C11'],
                      'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8, 9, 10, 11])

dicionario = {'ID':[10,11,12,13,14,],'NOME':['Mario','Joana','Claudia','Lucas','Gabriel'],
              'CIDADE':['SÃO PAULO','RIO DE JANEIRO','SÃO PAULO','CAMPINAS','PORTO ALEGRE']}
dicionario2 = {'ID':[16,11,12,13,18,],'Experiência':['Junior','Senior','Pleno','Estagiário','Analista']}

df4 = pd.DataFrame(data=dicionario)
df5 = pd.DataFrame(data=dicionario2)

dicionario = {'NOME':['Mario','Joana','Claudia','Lucas','Gabriel'],
              'CIDADE':['SÃO PAULO','RIO DE JANEIRO','SÃO PAULO','CAMPINAS','PORTO ALEGRE']}

dicionario2 = {'Experiência':['Junior','Senior','Pleno','Estagiário','Analista']}

df7 = pd.DataFrame(data=dicionario)
df8 = pd.DataFrame(data=dicionario2)

In [40]:
df_concat = pd.concat([df1, df2, df3])

In [41]:
df_concat

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [42]:
merge_inner = pd.merge(df4, df5)
merge_inner

   ID     NOME          CIDADE Experiência
0  11    Joana  RIO DE JANEIRO      Senior
1  12  Claudia       SÃO PAULO       Pleno
2  13    Lucas        CAMPINAS  Estagiário

In [43]:
merge_outer = pd.merge(df4, df5, how = 'outer')
merge_outer
# ou left, right.. -> junta por colunas em comum,

   ID     NOME          CIDADE Experiência
0  10    Mario       SÃO PAULO         NaN
1  11    Joana  RIO DE JANEIRO      Senior
2  12  Claudia       SÃO PAULO       Pleno
3  13    Lucas        CAMPINAS  Estagiário
4  14  Gabriel    PORTO ALEGRE         NaN
5  16      NaN             NaN      Junior
6  18      NaN             NaN    Analista

In [44]:
#o join junta por indices em comum
join = df4.join(df5, lsuffix = 'esq', rsuffix = 'dir' )
join

   IDesq     NOME          CIDADE  IDdir Experiência
0     10    Mario       SÃO PAULO     16      Junior
1     11    Joana  RIO DE JANEIRO     11      Senior
2     12  Claudia       SÃO PAULO     12       Pleno
3     13    Lucas        CAMPINAS     13  Estagiário
4     14  Gabriel    PORTO ALEGRE     18    Analista

In [45]:
join_leftesq = df7.join(df8)
join_leftesq

      NOME          CIDADE Experiência
0    Mario       SÃO PAULO      Junior
1    Joana  RIO DE JANEIRO      Senior
2  Claudia       SÃO PAULO       Pleno
3    Lucas        CAMPINAS  Estagiário
4  Gabriel    PORTO ALEGRE    Analista

In [47]:
#group by - similar ao SQL
data = {'Sede':['SP','SP','MG','MG','RJ','RJ','ES','ES'],
       'Vendedor':['Jorge','Ana','Tiago','Pedro','Raphaela','Guto','Maria','Carolina'],
       'Vendas':[2000,2500,3100,1200,1500,3900,2900,3900]}
dfgb = pd.DataFrame(data)

arrays = [['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Rio de Janeiro','Minas Gerais','Minas Gerais'],
['Garrafas','Copos','Garrafas','Copos','Garrafas','Copos' ]]
index = pd.MultiIndex.from_arrays(arrays, names=('Estado', 'Produto'))
dfgb1 = pd.DataFrame({'Total Vendido R$': [10000, 35000, 22400, 12890,10880,13900]},index=index)

In [48]:
dfgb

  Sede  Vendedor  Vendas
0   SP     Jorge    2000
1   SP       Ana    2500
2   MG     Tiago    3100
3   MG     Pedro    1200
4   RJ  Raphaela    1500
5   RJ      Guto    3900
6   ES     Maria    2900
7   ES  Carolina    3900

In [49]:
dfgb1

                         Total Vendido R$
Estado         Produto
São Paulo      Garrafas             10000
               Copos                35000
Rio de Janeiro Garrafas             22400
               Copos                12890
Minas Gerais   Garrafas             10880
               Copos                13900

In [53]:
by_sede = dfgb.groupby('Sede')
by_sede['Vendas'].mean()

Sede
ES    3400.0
MG    2150.0
RJ    2700.0
SP    2250.0
Name: Vendas, dtype: float64

In [54]:
by_sede.describe()

     Vendas
      count    mean          std     min     25%     50%     75%     max
Sede
ES      2.0  3400.0   707.106781  2900.0  3150.0  3400.0  3650.0  3900.0
MG      2.0  2150.0  1343.502884  1200.0  1675.0  2150.0  2625.0  3100.0
RJ      2.0  2700.0  1697.056275  1500.0  2100.0  2700.0  3300.0  3900.0
SP      2.0  2250.0   353.553391  2000.0  2125.0  2250.0  2375.0  2500.0

In [58]:
by_sede.describe().transpose()['SP']

Vendas  count       2.000000
        mean     2250.000000
        std       353.553391
        min      2000.000000
        25%      2125.000000
        50%      2250.000000
        75%      2375.000000
        max      2500.000000
Name: SP, dtype: float64

In [60]:
multi_byestado = dfgb1.groupby('Estado', level = 0)
multi_byestado['Total Vendido R$'].mean()

Estado
Minas Gerais      12390.0
Rio de Janeiro    17645.0
São Paulo         22500.0
Name: Total Vendido R$, dtype: float64

In [61]:
multi_byproduto = dfgb1.groupby('Produto', level=1)
multi_byproduto.mean()

          Total Vendido R$
Produto
Copos         20596.666667
Garrafas      14426.666667