In [1]:
import pandas as pd
import numpy as np
np.random.seed(100)

In [2]:
#series: é formatado em coluna, diferentemente dos arrays
s = pd.Series([1,2,3, 'ola',6,8])
s

0      1
1      2
2      3
3    ola
4      6
5      8
dtype: object

In [3]:
#series apartir de uma lista
lista = [10,20,30,40,50]

In [4]:
series1 = pd.Series(lista)

In [5]:
#series apartir de um dict
dicionario = {'telefone': 123, 'telefone2': 456, 'telefone3': 789}
series2 = pd.Series(dicionario)

In [6]:
series1[1]

np.int64(20)

In [7]:
series2['telefone3']

np.int64(789)

In [8]:
#series a partir de um array 
arr = np.array([10,20,30,40])
series3 = pd.Series(arr)
series3

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
series4 = pd.Series([1,2,3,4], index = ['br', 'arg', 'usa', 'chi'])

In [10]:
series4

br     1
arg    2
usa    3
chi    4
dtype: int64

In [11]:
series5 = pd.Series([7,8,9,10], index = ['br', 'arg', 'usa', 'uru'])

In [12]:
series4 + series5
#chi e uru nao tem valores nos dois series

arg    10.0
br      8.0
chi     NaN
uru     NaN
usa    12.0
dtype: float64

In [13]:
 #DATAFRAMES
# dataframes a partir de um array
arr = np.random.randint(10,55, size = (4,4))
arr

array([[18, 34, 13, 49],
       [33, 25, 20, 40],
       [44, 12, 44, 24],
       [44, 34, 25, 46]])

In [14]:
df1 = pd.DataFrame(data=arr, index=['a','b','c','d'], columns = ['x','y','z','w'])
df1

    x   y   z   w
a  18  34  13  49
b  33  25  20  40
c  44  12  44  24
d  44  34  25  46

In [15]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
df2 = pd.DataFrame(data=matriz, index=['a','b','c'], columns = ['d','e','f'])
df2

   d  e  f
a  1  2  3
b  4  5  6
c  7  8  9

In [16]:
#atraves de um dict
dados = {'Produtos': ['VideoGame', 'PC', 'Teclado', 'Mouse'], 'Preço': [5000.00, 4000.00, 150.00, 75.00]}
df3 = pd.DataFrame(data = dados)
df3

    Produtos   Preço
0  VideoGame  5000.0
1         PC  4000.0
2    Teclado   150.0
3      Mouse    75.0

In [17]:
df3['Custo'] = [3500.00, 2750.00, 45.00, 25.00]
df3['Lucro'] = df3['Preço'] - df3['Custo']
df3

    Produtos   Preço   Custo   Lucro
0  VideoGame  5000.0  3500.0  1500.0
1         PC  4000.0  2750.0  1250.0
2    Teclado   150.0    45.0   105.0
3      Mouse    75.0    25.0    50.0

In [18]:
indices = ['Janeiro', 'Março', 'Maio', 'Julho', 'Agosto', 'Outubro' ,'Dezembro']
colunas = np.arange(1,32)
dados = np.random.randint(492, 2050, size=(7,31))

In [19]:
df = pd.DataFrame(data=dados, index=indices, columns=colunas)
df

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Janeiro,1832,1404,2023,1609,578,878,907,1389,1657,1249,...,1852,494,1381,1109,970,1919,555,1697,775,1754
Março,1885,1436,1819,1298,664,766,684,1444,1422,929,...,1338,1516,505,1701,1976,854,623,1074,1728,886
Maio,1731,2018,987,1135,1365,1692,1696,528,1331,530,...,1772,1254,718,1407,688,938,1310,1968,911,899
Julho,1257,2037,1436,2012,901,1954,754,1638,1702,1811,...,1295,1532,2040,1982,1113,1583,712,1739,1280,630
Agosto,1268,965,1204,1930,1505,1865,1379,1048,1761,1573,...,1593,704,877,1530,1805,640,660,1993,934,1288
Outubro,1214,1994,1006,1067,1373,1646,1731,637,1753,1766,...,1377,1285,1710,1147,856,614,503,1105,1496,530
Dezembro,1315,805,579,1183,1246,998,1185,1197,1814,664,...,1834,957,1020,1586,1825,1486,1436,1397,1371,1166

In [20]:
#quanto vendeu no dia 10 dos meses
df[10]

Janeiro     1249
Março        929
Maio         530
Julho       1811
Agosto      1573
Outubro     1766
Dezembro     664
Name: 10, dtype: int64

tipos 

df[] muda de comportamento, pode procurar linhas ou colunas-> 
df.loc[] é consistente no padrão df.loc[linha,coluna]

df[coluna]
df[[coluna1, coluna2, coluna3]]
df[coluna][linha]
df[linha1: linha2]
df.loc[ind linha, indice coluna] -> df.loc['Julho', 30]
df.iloc[ind num linha, indice coluna]-> df.iloc[3, 30]
df.loc[[indlinha1, indlinha2, indlinha3], [col1, col2, col3]]

In [21]:
#quanto vendeu no dia 10,20 e 30 dos meses
df[10]

Janeiro     1249
Março        929
Maio         530
Julho       1811
Agosto      1573
Outubro     1766
Dezembro     664
Name: 10, dtype: int64

In [22]:
df[[10,20,30]]

            10    20    30
Janeiro   1249  1459   775
Março      929   967  1728
Maio       530  1430   911
Julho     1811   581  1280
Agosto    1573  1354   934
Outubro   1766  1145  1496
Dezembro   664   605  1371

In [23]:
df[15]['Março']

np.int64(509)

In [24]:
#quanto vendeu em Janeiro, Agosto e Outubro de 25 a 31 
df.loc[['Julho', 'Agosto', 'Outubro'], [25, 26,27,28,29,30,31]]
df.iloc[[3,4,5], [24,25,26,27,28,29,30]]

           25    26    27   28    29    30    31
Julho    1982  1113  1583  712  1739  1280   630
Agosto   1530  1805   640  660  1993   934  1288
Outubro  1147   856   614  503  1105  1496   530

In [25]:
#selecoes condicionais
df.rename({'Janeiro':'Porta'}, inplace = True)

In [26]:
df

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Porta,1832,1404,2023,1609,578,878,907,1389,1657,1249,...,1852,494,1381,1109,970,1919,555,1697,775,1754
Março,1885,1436,1819,1298,664,766,684,1444,1422,929,...,1338,1516,505,1701,1976,854,623,1074,1728,886
Maio,1731,2018,987,1135,1365,1692,1696,528,1331,530,...,1772,1254,718,1407,688,938,1310,1968,911,899
Julho,1257,2037,1436,2012,901,1954,754,1638,1702,1811,...,1295,1532,2040,1982,1113,1583,712,1739,1280,630
Agosto,1268,965,1204,1930,1505,1865,1379,1048,1761,1573,...,1593,704,877,1530,1805,640,660,1993,934,1288
Outubro,1214,1994,1006,1067,1373,1646,1731,637,1753,1766,...,1377,1285,1710,1147,856,614,503,1105,1496,530
Dezembro,1315,805,579,1183,1246,998,1185,1197,1814,664,...,1834,957,1020,1586,1825,1486,1436,1397,1371,1166

In [28]:
df[df > 1000].fillna('-')

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Porta,1832,1404.0,2023.0,1609,-,-,-,1389.0,1657,1249.0,...,1852,-,1381.0,1109,-,1919.0,-,1697,-,1754.0
Março,1885,1436.0,1819.0,1298,-,-,-,1444.0,1422,-,...,1338,1516.0,-,1701,1976.0,-,-,1074,1728.0,-
Maio,1731,2018.0,-,1135,1365.0,1692.0,1696.0,-,1331,-,...,1772,1254.0,-,1407,-,-,1310.0,1968,-,-
Julho,1257,2037.0,1436.0,2012,-,1954.0,-,1638.0,1702,1811.0,...,1295,1532.0,2040.0,1982,1113.0,1583.0,-,1739,1280.0,-
Agosto,1268,-,1204.0,1930,1505.0,1865.0,1379.0,1048.0,1761,1573.0,...,1593,-,-,1530,1805.0,-,-,1993,-,1288.0
Outubro,1214,1994.0,1006.0,1067,1373.0,1646.0,1731.0,-,1753,1766.0,...,1377,1285.0,1710.0,1147,-,-,-,1105,1496.0,-
Dezembro,1315,-,-,1183,1246.0,-,1185.0,1197.0,1814,-,...,1834,-,1020.0,1586,1825.0,1486.0,1436.0,1397,1371.0,1166.0

In [33]:
df[df>1000][:][[1,2,3,4,5]].fillna('')

             1       2       3     4       5
Porta     1832  1404.0  2023.0  1609
Março     1885  1436.0  1819.0  1298
Maio      1731  2018.0          1135  1365.0
Julho     1257  2037.0  1436.0  2012
Agosto    1268          1204.0  1930  1505.0
Outubro   1214  1994.0  1006.0  1067  1373.0
Dezembro  1315                  1183  1246.0

In [36]:
df[(df[10] > 1000) & (df[15]>1500)].fillna('')

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Agosto,1268,965,1204,1930,1505,1865,1379,1048,1761,1573,...,1593,704,877,1530,1805,640,660,1993,934,1288
Outubro,1214,1994,1006,1067,1373,1646,1731,637,1753,1766,...,1377,1285,1710,1147,856,614,503,1105,1496,530

In [37]:
df[(df[10] > 1000) | (df[15]>1500)].fillna('')

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Porta,1832,1404,2023,1609,578,878,907,1389,1657,1249,...,1852,494,1381,1109,970,1919,555,1697,775,1754
Julho,1257,2037,1436,2012,901,1954,754,1638,1702,1811,...,1295,1532,2040,1982,1113,1583,712,1739,1280,630
Agosto,1268,965,1204,1930,1505,1865,1379,1048,1761,1573,...,1593,704,877,1530,1805,640,660,1993,934,1288
Outubro,1214,1994,1006,1067,1373,1646,1731,637,1753,1766,...,1377,1285,1710,1147,856,614,503,1105,1496,530