In [1]:
import pandas as pd
import numpy as np

In [2]:
#series: é formatado em coluna, diferentemente dos arrays
s = pd.Series([1,2,3, 'ola',6,8])
s

0      1
1      2
2      3
3    ola
4      6
5      8
dtype: object

In [3]:
#series apartir de uma lista
lista = [10,20,30,40,50]

In [4]:
series1 = pd.Series(lista)

In [5]:
#series apartir de um dict
dicionario = {'telefone': 123, 'telefone2': 456, 'telefone3': 789}
series2 = pd.Series(dicionario)

In [6]:
series1[1]

np.int64(20)

In [7]:
series2['telefone3']

np.int64(789)

In [8]:
#series a partir de um array 
arr = np.array([10,20,30,40])
series3 = pd.Series(arr)
series3

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
series4 = pd.Series([1,2,3,4], index = ['br', 'arg', 'usa', 'chi'])

In [10]:
series4

br     1
arg    2
usa    3
chi    4
dtype: int64

In [11]:
series5 = pd.Series([7,8,9,10], index = ['br', 'arg', 'usa', 'uru'])

In [12]:
series4 + series5
#chi e uru nao tem valores nos dois series

arg    10.0
br      8.0
chi     NaN
uru     NaN
usa    12.0
dtype: float64

In [14]:
 #DATAFRAMES
# dataframes a partir de um array
arr = np.random.randint(10,55, size = (4,4))
arr

array([[23, 10, 20, 38],
       [47, 11, 37, 41],
       [10, 40, 53, 23],
       [31, 11, 29, 20]])

In [17]:
df1 = pd.DataFrame(data=arr, index=['a','b','c','d'], columns = ['x','y','z','w'])
df1

    x   y   z   w
a  23  10  20  38
b  47  11  37  41
c  10  40  53  23
d  31  11  29  20

In [19]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
df2 = pd.DataFrame(data=matriz, index=['a','b','c'], columns = ['d','e','f'])
df2

   d  e  f
a  1  2  3
b  4  5  6
c  7  8  9

In [22]:
#atraves de um dict
dados = {'Produtos': ['VideoGame', 'PC', 'Teclado', 'Mouse'], 'Preço': [5000.00, 4000.00, 150.00, 75.00]}
df3 = pd.DataFrame(data = dados)
df3

    Produtos   Preço
0  VideoGame  5000.0
1         PC  4000.0
2    Teclado   150.0
3      Mouse    75.0

In [25]:
df3['Custo'] = [3500.00, 2750.00, 45.00, 25.00]
df3['Lucro'] = df3['Preço'] - df3['Custo']
df3

    Produtos   Preço   Custo   Lucro
0  VideoGame  5000.0  3500.0  1500.0
1         PC  4000.0  2750.0  1250.0
2    Teclado   150.0    45.0   105.0
3      Mouse    75.0    25.0    50.0