In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('campeonato_brasileiro.csv')
df = df.replace('Empate', np.nan)
df.head()

,Horário,Dia,Data,Clube 1,Clube 2,Vencedor,Rodada,Arena,Clube 1 Gols,Clube 2 Gols,Clube 1 Estado,Clube 2 Estado,Estado Clube Vencedor
0,16:00,Domingo,13/04/2025,Flamengo,Bahia,Flamengo,1,Maracanã,3,1,RJ,BA,RJ
1,21:30,Sábado,12/04/2025,Internacional,Fluminense,Internacional,1,Beira-Rio,2,1,RS,RJ,RS
2,16:00,Sábado,12/04/2025,Palmeiras,Grêmio,Palmeiras,1,Allianz Parque,2,1,SP,RS,SP
3,21:30,Domingo,13/04/2025,Cruzeiro,Corinthians,NaN,1,Mineirão,1,1,MG,SP,NaN
4,18:30,Domingo,13/04/2025,São Paulo,Atlético-MG,São Paulo,1,MorumBIS,3,1,SP,MG,SP

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Horário                45 non-null     str
 1   Dia                    45 non-null     str
 2   Data                   45 non-null     str
 3   Clube 1                45 non-null     str
 4   Clube 2                45 non-null     str
 5   Vencedor               33 non-null     str
 6   Rodada                 45 non-null     int64
 7   Arena                  45 non-null     str
 8   Clube 1 Gols           45 non-null     int64
 9   Clube 2 Gols           45 non-null     int64
 10  Clube 1 Estado         45 non-null     str
 11  Clube 2 Estado         45 non-null     str
 12  Estado Clube Vencedor  33 non-null     str
dtypes: int64(3), str(10)
memory usage: 4.7 KB

In [4]:
#qual a média de gols do mandante
df['Clube 1 Gols'].mean()

np.float64(1.3111111111111111)

In [5]:
#media total de gols
df['Total de Gols'] = df['Clube 1 Gols']+df['Clube 2 Gols']
df['Total de Gols'].mean()

np.float64(2.2)

In [6]:
#qual time mais venceu ?
df['Vencedor'].value_counts()

Vencedor
Flamengo         6
Internacional    4
São Paulo        4
Bahia            4
Grêmio           4
Palmeiras        3
Atlético-MG      3
Corinthians      2
Cruzeiro         2
Fluminense       1
Name: count, dtype: int64

In [7]:
#qual estado mais ganhou ? 
df['Estado Clube Vencedor'].value_counts()

Estado Clube Vencedor
SP    9
RS    8
RJ    7
MG    5
BA    4
Name: count, dtype: int64

In [8]:
#ordenação de valores
#qual o maior numero de um mandante em um jogo
df.sort_values(by='Clube 1 Gols', ascending = False)

,Horário,Dia,Data,Clube 1,Clube 2,Vencedor,Rodada,Arena,Clube 1 Gols,Clube 2 Gols,Clube 1 Estado,Clube 2 Estado,Estado Clube Vencedor,Total de Gols
22,19:00,Domingo,11/05/2025,Grêmio,Corinthians,Grêmio,5,Arena do Grêmio,4,1,RS,SP,RS,5
4,18:30,Domingo,13/04/2025,São Paulo,Atlético-MG,São Paulo,1,MorumBIS,3,1,SP,MG,SP,4
5,20:00,Domingo,20/04/2025,Internacional,Flamengo,Internacional,2,Beira-Rio,3,1,RS,RJ,RS,4
39,16:00,Sábado,31/05/2025,Grêmio,Cruzeiro,Grêmio,8,Arena do Grêmio,3,1,RS,MG,RS,4
0,16:00,Domingo,13/04/2025,Flamengo,Bahia,Flamengo,1,Maracanã,3,1,RJ,BA,RJ,4
32,19:00,Domingo,25/05/2025,Atlético-MG,Fluminense,Atlético-MG,7,Arena MRV,3,1,MG,RJ,MG,4
42,20:00,Domingo,08/06/2025,Corinthians,Internacional,Corinthians,9,Neo Química Arena,3,1,SP,RS,SP,4
38,21:30,Sábado,31/05/2025,Atlético-MG,Internacional,Atlético-MG,8,Arena MRV,3,2,MG,RS,MG,5
13,18:30,Sábado,26/04/2025,São Paulo,Fluminense,São Paulo,3,MorumBIS,2,0,SP,RJ,SP,2
6,18:30,Sábado,19/04/2025,Bahia,Grêmio,Bahia,2,Arena Fonte Nova,2,1,BA,RS,BA,3
23,20:00,Domingo,11/05/2025,Palmeiras,Internacional,Palmeiras,5,Allianz Parque,2,0,SP,RS,SP,2
2,16:00,Sábado,12/04/2025,Palmeiras,Grêmio,Palmeiras,1,Allianz Parque,2,1,SP,RS,SP,3
1,21:30,Sábado,12/04/2025,Internacional,Fluminense,Internacional,1,Beira-Rio,2,1,RS,RJ,RS,3
25,18:30,Sábado,17/05/2025,São Paulo,Flamengo,São Paulo,6,MorumBIS,2,0,SP,RJ,SP,2
24,16:00,Domingo,11/05/2025,Bahia,Fluminense,Bahia,5,Arena Fonte Nova,2,1,BA,RJ,BA,3
30,18:30,Sábado,24/05/2025,Flamengo,Corinthians,Flamengo,7,Maracanã,2,1,RJ,SP,RJ,3
43,19:00,Domingo,08/06/2025,Grêmio,São Paulo,Grêmio,9,Arena do Grêmio,2,1,RS,SP,RS,3
28,20:00,Domingo,18/05/2025,Grêmio,Fluminense,Grêmio,6,Arena do Grêmio,2,0,RS,RJ,RS,2
20,19:00,Domingo,11/05/2025,Flamengo,Atlético-MG,Flamengo,5,Maracanã,2,1,RJ,MG,RJ,3
3,21:30,Domingo,13/04/2025,Cruzeiro,Corinthians,NaN,1,Mineirão,1,1,MG,SP,NaN,2
10,21:30,Domingo,27/04/2025,Flamengo,Grêmio,Flamengo,3,Maracanã,1,0,RJ,RS,RJ,1
40,19:00,Sábado,07/06/2025,Flamengo,Fluminense,NaN,9,Maracanã,1,1,RJ,RJ,NaN,2
37,21:30,Sábado,31/05/2025,Bahia,São Paulo,NaN,8,Arena Fonte Nova,1,1,BA,SP,NaN,2
41,16:00,Domingo,08/06/2025,Bahia,Palmeiras,Bahia,9,Arena Fonte Nova,1,0,BA,SP,BA,1
35,16:00,Domingo,01/06/2025,Palmeiras,Flamengo,Flamengo,8,Allianz Parque,1,2,SP,RJ,RJ,3
9,16:00,Domingo,20/04/2025,São Paulo,Corinthians,NaN,2,MorumBIS,1,1,SP,SP,NaN,2
21,19:00,Domingo,11/05/2025,São Paulo,Cruzeiro,NaN,5,MorumBIS,1,1,SP,MG,NaN,2
15,16:00,Domingo,04/05/2025,Cruzeiro,Flamengo,Flamengo,4,Mineirão,1,4,MG,RJ,RJ,5
19,21:30,Domingo,04/05/2025,Palmeiras,Fluminense,Palmeiras,4,Allianz Parque,1,0,SP,RJ,SP,1
29,18:30,Domingo,18/05/2025,Bahia,Internacional,Bahia,6,Arena Fonte Nova,1,0,BA,RS,BA,1
36,16:00,Domingo,01/06/2025,Corinthians,Fluminense,NaN,8,Neo Química Arena,1,1,SP,RJ,NaN,2
7,21:30,Domingo,20/04/2025,Cruzeiro,Fluminense,Fluminense,2,Mineirão,0,2,MG,RJ,RJ,2
8,16:00,Domingo,20/04/2025,Palmeiras,Atlético-MG,NaN,2,Allianz Parque,0,0,SP,MG,NaN,0
12,19:00,Domingo,27/04/2025,Bahia,Atlético-MG,NaN,3,Arena Fonte Nova,0,0,BA,MG,NaN,0
11,19:00,Sábado,26/04/2025,Cruzeiro,Internacional,Internacional,3,Mineirão,0,1,MG,RS,RS,1
16,18:30,Domingo,04/05/2025,Grêmio,Atlético-MG,Atlético-MG,4,Arena do Grêmio,0,2,RS,MG,MG,2
14,19:00,Sábado,26/04/2025,Palmeiras,Corinthians,NaN,3,Allianz Parque,0,0,SP,SP,NaN,0
27,18:30,Sábado,17/05/2025,Palmeiras,Cruzeiro,Cruzeiro,6,Allianz Parque,0,1,SP,MG,MG,1
26,16:00,Domingo,18/05/2025,Atlético-MG,Corinthians,Corinthians,6,Arena MRV,0,2,MG,SP,SP,2
18,19:00,Domingo,04/05/2025,Bahia,Corinthians,NaN,4,Arena Fonte Nova,0,0,BA,SP,NaN,0
17,16:00,Domingo,04/05/2025,São Paulo,Internacional,Internacional,4,MorumBIS,0,2,SP,RS,RS,2
33,21:30,Domingo,25/05/2025,Bahia,Cruzeiro,NaN,7,Arena Fonte Nova,0,0,BA,MG,NaN,0
34,20:00,Domingo,25/05/2025,Grêmio,Internacional,NaN,7,Arena do Grêmio,0,0,RS,RS,NaN,0
31,19:00,Sábado,24/05/2025,Palmeiras,São Paulo,São Paulo,7,Allianz Parque,0,1,SP,SP,SP,1
44,21:30,Domingo,08/06/2025,Atlético-MG,Cruzeiro,Cruzeiro,9,Arena MRV,0,1,MG,MG,MG,1

In [9]:
#qual a maior goleada ? 
df['Diferença de Gols'] = (df['Clube 1 Gols'] - df['Clube 2 Gols']).abs()

In [10]:
df.sort_values(by='Diferença de Gols', ascending = False)

,Horário,Dia,Data,Clube 1,Clube 2,Vencedor,Rodada,Arena,Clube 1 Gols,Clube 2 Gols,Clube 1 Estado,Clube 2 Estado,Estado Clube Vencedor,Total de Gols,Diferença de Gols
15,16:00,Domingo,04/05/2025,Cruzeiro,Flamengo,Flamengo,4,Mineirão,1,4,MG,RJ,RJ,5,3
22,19:00,Domingo,11/05/2025,Grêmio,Corinthians,Grêmio,5,Arena do Grêmio,4,1,RS,SP,RS,5,3
5,20:00,Domingo,20/04/2025,Internacional,Flamengo,Internacional,2,Beira-Rio,3,1,RS,RJ,RS,4,2
4,18:30,Domingo,13/04/2025,São Paulo,Atlético-MG,São Paulo,1,MorumBIS,3,1,SP,MG,SP,4,2
0,16:00,Domingo,13/04/2025,Flamengo,Bahia,Flamengo,1,Maracanã,3,1,RJ,BA,RJ,4,2
17,16:00,Domingo,04/05/2025,São Paulo,Internacional,Internacional,4,MorumBIS,0,2,SP,RS,RS,2,2
23,20:00,Domingo,11/05/2025,Palmeiras,Internacional,Palmeiras,5,Allianz Parque,2,0,SP,RS,SP,2,2
26,16:00,Domingo,18/05/2025,Atlético-MG,Corinthians,Corinthians,6,Arena MRV,0,2,MG,SP,SP,2,2
25,18:30,Sábado,17/05/2025,São Paulo,Flamengo,São Paulo,6,MorumBIS,2,0,SP,RJ,SP,2,2
13,18:30,Sábado,26/04/2025,São Paulo,Fluminense,São Paulo,3,MorumBIS,2,0,SP,RJ,SP,2,2
16,18:30,Domingo,04/05/2025,Grêmio,Atlético-MG,Atlético-MG,4,Arena do Grêmio,0,2,RS,MG,MG,2,2
7,21:30,Domingo,20/04/2025,Cruzeiro,Fluminense,Fluminense,2,Mineirão,0,2,MG,RJ,RJ,2,2
28,20:00,Domingo,18/05/2025,Grêmio,Fluminense,Grêmio,6,Arena do Grêmio,2,0,RS,RJ,RS,2,2
39,16:00,Sábado,31/05/2025,Grêmio,Cruzeiro,Grêmio,8,Arena do Grêmio,3,1,RS,MG,RS,4,2
42,20:00,Domingo,08/06/2025,Corinthians,Internacional,Corinthians,9,Neo Química Arena,3,1,SP,RS,SP,4,2
32,19:00,Domingo,25/05/2025,Atlético-MG,Fluminense,Atlético-MG,7,Arena MRV,3,1,MG,RJ,MG,4,2
43,19:00,Domingo,08/06/2025,Grêmio,São Paulo,Grêmio,9,Arena do Grêmio,2,1,RS,SP,RS,3,1
10,21:30,Domingo,27/04/2025,Flamengo,Grêmio,Flamengo,3,Maracanã,1,0,RJ,RS,RJ,1,1
6,18:30,Sábado,19/04/2025,Bahia,Grêmio,Bahia,2,Arena Fonte Nova,2,1,BA,RS,BA,3,1
2,16:00,Sábado,12/04/2025,Palmeiras,Grêmio,Palmeiras,1,Allianz Parque,2,1,SP,RS,SP,3,1
11,19:00,Sábado,26/04/2025,Cruzeiro,Internacional,Internacional,3,Mineirão,0,1,MG,RS,RS,1,1
1,21:30,Sábado,12/04/2025,Internacional,Fluminense,Internacional,1,Beira-Rio,2,1,RS,RJ,RS,3,1
44,21:30,Domingo,08/06/2025,Atlético-MG,Cruzeiro,Cruzeiro,9,Arena MRV,0,1,MG,MG,MG,1,1
38,21:30,Sábado,31/05/2025,Atlético-MG,Internacional,Atlético-MG,8,Arena MRV,3,2,MG,RS,MG,5,1
29,18:30,Domingo,18/05/2025,Bahia,Internacional,Bahia,6,Arena Fonte Nova,1,0,BA,RS,BA,1,1
27,18:30,Sábado,17/05/2025,Palmeiras,Cruzeiro,Cruzeiro,6,Allianz Parque,0,1,SP,MG,MG,1,1
24,16:00,Domingo,11/05/2025,Bahia,Fluminense,Bahia,5,Arena Fonte Nova,2,1,BA,RJ,BA,3,1
19,21:30,Domingo,04/05/2025,Palmeiras,Fluminense,Palmeiras,4,Allianz Parque,1,0,SP,RJ,SP,1,1
20,19:00,Domingo,11/05/2025,Flamengo,Atlético-MG,Flamengo,5,Maracanã,2,1,RJ,MG,RJ,3,1
35,16:00,Domingo,01/06/2025,Palmeiras,Flamengo,Flamengo,8,Allianz Parque,1,2,SP,RJ,RJ,3,1
41,16:00,Domingo,08/06/2025,Bahia,Palmeiras,Bahia,9,Arena Fonte Nova,1,0,BA,SP,BA,1,1
30,18:30,Sábado,24/05/2025,Flamengo,Corinthians,Flamengo,7,Maracanã,2,1,RJ,SP,RJ,3,1
31,19:00,Sábado,24/05/2025,Palmeiras,São Paulo,São Paulo,7,Allianz Parque,0,1,SP,SP,SP,1,1
12,19:00,Domingo,27/04/2025,Bahia,Atlético-MG,NaN,3,Arena Fonte Nova,0,0,BA,MG,NaN,0,0
9,16:00,Domingo,20/04/2025,São Paulo,Corinthians,NaN,2,MorumBIS,1,1,SP,SP,NaN,2,0
8,16:00,Domingo,20/04/2025,Palmeiras,Atlético-MG,NaN,2,Allianz Parque,0,0,SP,MG,NaN,0,0
3,21:30,Domingo,13/04/2025,Cruzeiro,Corinthians,NaN,1,Mineirão,1,1,MG,SP,NaN,2,0
21,19:00,Domingo,11/05/2025,São Paulo,Cruzeiro,NaN,5,MorumBIS,1,1,SP,MG,NaN,2,0
18,19:00,Domingo,04/05/2025,Bahia,Corinthians,NaN,4,Arena Fonte Nova,0,0,BA,SP,NaN,0,0
14,19:00,Sábado,26/04/2025,Palmeiras,Corinthians,NaN,3,Allianz Parque,0,0,SP,SP,NaN,0,0
33,21:30,Domingo,25/05/2025,Bahia,Cruzeiro,NaN,7,Arena Fonte Nova,0,0,BA,MG,NaN,0,0
36,16:00,Domingo,01/06/2025,Corinthians,Fluminense,NaN,8,Neo Química Arena,1,1,SP,RJ,NaN,2,0
34,20:00,Domingo,25/05/2025,Grêmio,Internacional,NaN,7,Arena do Grêmio,0,0,RS,RS,NaN,0,0
40,19:00,Sábado,07/06/2025,Flamengo,Fluminense,NaN,9,Maracanã,1,1,RJ,RJ,NaN,2,0
37,21:30,Sábado,31/05/2025,Bahia,São Paulo,NaN,8,Arena Fonte Nova,1,1,BA,SP,NaN,2,0

Task 1: Exploração inicial
Carregue o CSV, converta a coluna Data para datetime e responda:
Quantas linhas e colunas o DataFrame tem?
Quais são os tipos de cada coluna?
Qual foi o primeiro e o último dia do campeonato?
Dica: df.shape, df.dtypes, .min() e .max().

Task 2: Filtros e contagem
Liste todos os jogos que terminaram em empate.
Quantos jogos foram disputados em cada dia da semana?
Quantos jogos tiveram 3 gols ou mais no total?
Dica: filtro booleano, value_counts() e uma nova coluna Total Gols.

Task 3: Groupby
Qual é o total de gols marcados como mandante por clube?
Qual é a média de gols do mandante por estado?
Qual arena recebeu mais gols no total (somando os dois times)?
Dica: groupby, .sum(), .mean() e .agg().

Task 4: Numpy
Crie a coluna Resultado Mandante usando np.where (ou np.select), com os valores "Vitória", "Empate" ou "Derrota". Depois:
Use np.mean para calcular o percentual de vitórias dos mandantes no campeonato.
Use np.percentile para achar o percentil 75 do total de gols por jogo.
Use np.corrcoef para ver a correlação entre Clube 1 Gols e Clube 2 Gols.

Task 5: Classificação completa
Monte a tabela de classificação do campeonato, com as colunas: Clube, Jogos, Vitórias, Empates, Derrotas, Gols Pró, Gols Contra, Saldo e Pontos (3 por vitória, 1 por empate), ordenada por pontos, depois saldo de gols, depois gols pró.
O desafio é que cada clube aparece ora em Clube 1, ora em Clube 2, então você vai precisar juntar as duas visões. Uma estratégia: criar um DataFrame com os jogos do ponto de vista de cada time (com pd.concat) e depois aplicar groupby.

In [11]:
#Task 1
df['Data'] = pd.to_datetime(df['Data'], format='%d/%m/%Y')
df.info()
#depois das alterações que eu fiz: 15 colunas e 45 linhas
date_max = df['Data'].max()
date_min = df['Data'].min()

<class 'pandas.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Horário                45 non-null     str
 1   Dia                    45 non-null     str
 2   Data                   45 non-null     datetime64[us]
 3   Clube 1                45 non-null     str
 4   Clube 2                45 non-null     str
 5   Vencedor               33 non-null     str
 6   Rodada                 45 non-null     int64
 7   Arena                  45 non-null     str
 8   Clube 1 Gols           45 non-null     int64
 9   Clube 2 Gols           45 non-null     int64
 10  Clube 1 Estado         45 non-null     str
 11  Clube 2 Estado         45 non-null     str
 12  Estado Clube Vencedor  33 non-null     str
 13  Total de Gols          45 non-null     int64
 14  Diferença de Gols      45 non-null     int64
dtypes: datetime64[us](1), int64(5), str(9)
memory usage: 5.4 KB

In [14]:
#task 2
df[df['Vencedor'].isna()]
df['Dia'].value_counts()
#31 no domingo e 14 no sabado
df_mais3 = df[df['Total de Gols'] >= 3] 
df_mais3.info()
#17 jogos 
# ou (df['Total de Gols'] >= 3).sum() -> soma os true

<class 'pandas.DataFrame'>
Index: 17 entries, 0 to 43
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Horário                17 non-null     str
 1   Dia                    17 non-null     str
 2   Data                   17 non-null     datetime64[us]
 3   Clube 1                17 non-null     str
 4   Clube 2                17 non-null     str
 5   Vencedor               17 non-null     str
 6   Rodada                 17 non-null     int64
 7   Arena                  17 non-null     str
 8   Clube 1 Gols           17 non-null     int64
 9   Clube 2 Gols           17 non-null     int64
 10  Clube 1 Estado         17 non-null     str
 11  Clube 2 Estado         17 non-null     str
 12  Estado Clube Vencedor  17 non-null     str
 13  Total de Gols          17 non-null     int64
 14  Diferença de Gols      17 non-null     int64
dtypes: datetime64[us](1), int64(5), str(9)
memory usage: 2.1 KB

In [44]:
#task5
posicoes = [1,2,3,4,5,6,7,8,9,10]
colunas = ['Clube','Pontos','Jogos','Vitórias','Empates','Derrotas','Gols Pró','Gols Contra','Saldo']
dfc = pd.DataFrame(index=posicoes, columns=colunas)
dfc['Clube'] = clubes = list(pd.concat([df['Clube 1'], df['Clube 2']]).unique())

for i, clube in zip(dfc.index, dfc['Clube']):
    casa = df[df['Clube 1'] == clube]   # jogos como mandante
    fora = df[df['Clube 2'] == clube]   # jogos como visitante

    gp = casa['Clube 1 Gols'].sum() + fora['Clube 2 Gols'].sum()
    gc = casa['Clube 2 Gols'].sum() + fora['Clube 1 Gols'].sum()
    v = (casa['Clube 1 Gols'] > casa['Clube 2 Gols']).sum() + (fora['Clube 2 Gols'] > fora['Clube 1 Gols']).sum()
    e = (casa['Clube 1 Gols'] == casa['Clube 2 Gols']).sum() + (fora['Clube 2 Gols'] == fora['Clube 1 Gols']).sum()
    j = len(casa) + len(fora)

    dfc.loc[i, ['Jogos','Vitórias','Empates','Derrotas','Gols Pró','Gols Contra']] = [j, v, e, j-v-e, gp, gc]

dfc['Pontos'] = dfc['Vitórias']*3 + dfc['Empates']
dfc['Saldo'] = dfc['Gols Pró'] - dfc['Gols Contra']
dfc = dfc.astype({c: int for c in colunas[1:]})

dfc = dfc.sort_values(['Pontos','Saldo','Gols Pró'], ascending=False).reset_index(drop=True)
dfc.index = dfc.index + 1
dfc

,Clube,Pontos,Jogos,Vitórias,Empates,Derrotas,Gols Pró,Gols Contra,Saldo
1,Flamengo,19,9,6,1,2,16,11,5
2,Bahia,16,9,4,4,1,8,6,2
3,São Paulo,15,9,4,3,2,12,8,4
4,Grêmio,13,9,4,1,4,13,10,3
5,Internacional,13,9,4,1,4,11,11,0
6,Corinthians,11,9,2,5,2,10,10,0
7,Palmeiras,11,9,3,2,4,6,6,0
8,Atlético-MG,11,9,3,2,4,10,11,-1
9,Cruzeiro,9,9,2,3,4,6,12,-6
10,Fluminense,5,9,1,2,6,7,14,-7